apiVersion: v1
kind: Service
metadata:
  name: kafka-phoenix-ext
  namespace: phoenix
  labels:
    app.kubernetes.io/name: kafka-phoenix-ext
spec:
  selector:
    app.kubernetes.io/name: kafka-phoenix-ext
  ports:
    - name: http
      port: 8080
      targetPort: http